01: Update the workflow with second job.

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -6,5 +6,13 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: "Say hello"
+        run: echo "Hello, world!"
+  echo-goodbye:
+    runs-on: ubuntu-latest
+    steps:
+      - name: "Failed step"
         run: |
-          echo "Hello, world!"
+          echo "I will fail!"
+          exit 1
+      - name: "Say goodbye"
+        run: echo "Goodbye!"
